CREATE TABLE OWS_LIKES_USERS 
(
  LIKES_USERS_ID NUMBER NOT NULL 
, USERNAME VARCHAR2(25) NOT NULL 
, LIKES_ID NUMBER NOT NULL 
, CONSTRAINT OWS_LIKES_USERS_PK PRIMARY KEY 
  (
    LIKES_USERS_ID 
  )
  ENABLE 
);

ALTER TABLE OWS_LIKES_USERS
ADD CONSTRAINT OWS_LIKES_USERS_OWS_LIKES_FK1 FOREIGN KEY
(
  LIKES_ID 
)
REFERENCES OWS_LIKES
(
  LIKES_ID 
)
ON DELETE CASCADE ENABLE;
