CREATE TABLE OWS_ADVERTISEMENTS 
(
  ADVERTISEMENT_ID NUMBER NOT NULL 
, TITLE VARCHAR2(50) NOT NULL 
, INFORMATION VARCHAR2(200) NOT NULL 
, CREATE_DATE DATE DEFAULT sysdate 
, ADVERTISEMENT_STATUS VARCHAR2(3) DEFAULT 'WAP' NOT NULL 
, CREATOR_USER_ID NUMBER NOT NULL 
, CONSTRAINT OWS_ADVERTISEMENTS_PK PRIMARY KEY 
  (
    ADVERTISEMENT_ID 
  )
  ENABLE 
);

ALTER TABLE OWS_ADVERTISEMENTS
ADD CONSTRAINT OWS_ADVERTISEMENTS_OWS_US_FK1 FOREIGN KEY
(
  CREATOR_USER_ID 
)
REFERENCES OWS_USERS
(
  USER_ID 
)
ON DELETE CASCADE ENABLE;

COMMENT ON COLUMN OWS_ADVERTISEMENTS.ADVERTISEMENT_STATUS IS 'WAP = waiting approval
APR = approved
DEL = deleted
RJT = rejected';
